package br.com.bemdoar.service;
import br.com.bemdoar.dto.*;import br.com.bemdoar.entity.*;import br.com.bemdoar.enums.*;import br.com.bemdoar.exception.*;import br.com.bemdoar.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class AcaoSocialService{private final AcaoSocialRepository repo;private final EvidenciaRepository evidencias;private final CampanhaRepository campanhas;private final NecessidadeRepository necessidades;private final ParticipacaoVoluntarioRepository participacoes;public AcaoSocialService(AcaoSocialRepository r,EvidenciaRepository e,CampanhaRepository c,NecessidadeRepository n,ParticipacaoVoluntarioRepository p){repo=r;evidencias=e;campanhas=c;necessidades=n;participacoes=p;}private AcaoSocial get(Long id){return repo.findById(id).orElseThrow(()->new RecursoNaoEncontradoException("Acao social nao encontrada."));}private AcaoSocialResponse out(AcaoSocial a,boolean admin){return AcaoSocialResponse.de(a,admin?evidencias.findByAcaoId(a.getId()):evidencias.findByAcaoIdAndPublicaTrue(a.getId()));}
 @Transactional(readOnly=true)public List<AcaoSocialResponse> listar(boolean admin){return repo.findAllByOrderByDataInicioDesc().stream().map(a->out(a,admin)).toList();}@Transactional(readOnly=true)public AcaoSocialResponse buscar(Long id,boolean admin){return out(get(id),admin);}
 @Transactional public AcaoSocialResponse criar(AcaoSocialRequest q){validar(q);AcaoSocial a=new AcaoSocial();copiar(a,q);a.setSituacao(SituacaoAcaoSocial.PLANEJADA);return out(repo.save(a),true);}
 @Transactional public AcaoSocialResponse editar(Long id,AcaoSocialRequest q){AcaoSocial a=get(id);if(a.getSituacao()==SituacaoAcaoSocial.REALIZADA)throw new RegraNegocioException("A acao realizada nao pode ter o planejamento alterado por este fluxo.");if(a.getSituacao()==SituacaoAcaoSocial.CANCELADA)invalida();validar(q);copiar(a,q);return out(repo.save(a),true);}
 @Transactional public AcaoSocialResponse realizar(Long id){AcaoSocial a=get(id);if(a.getSituacao()!=SituacaoAcaoSocial.PLANEJADA)invalida();a.setSituacao(SituacaoAcaoSocial.REALIZADA);return out(repo.save(a),true);}@Transactional public AcaoSocialResponse cancelar(Long id){AcaoSocial a=get(id);if(a.getSituacao()!=SituacaoAcaoSocial.PLANEJADA)invalida();a.setSituacao(SituacaoAcaoSocial.CANCELADA);return out(repo.save(a),true);}
 @Transactional public AcaoSocialResponse resultado(Long id,ResultadoAcaoRequest q){AcaoSocial a=get(id);if(a.getSituacao()!=SituacaoAcaoSocial.REALIZADA)throw new RegraNegocioException("Somente acoes realizadas podem receber resultado.");a.setDescricaoResultado(q.descricaoResultado());a.setBeneficiadosReais(q.beneficiadosReais());return out(repo.save(a),true);}
 @Transactional public AcaoSocialResponse vincularCampanha(Long id,Long cid){AcaoSocial a=get(id);Campanha c=campanhas.findById(cid).orElseThrow(()->new RecursoNaoEncontradoException("Campanha nao encontrada."));if(!a.getCampanhas().add(c))throw new RegraNegocioException("Este vinculo ja existe.");return out(repo.save(a),true);}@Transactional public AcaoSocialResponse vincularNecessidade(Long id,Long nid){AcaoSocial a=get(id);Necessidade n=necessidades.findById(nid).orElseThrow(()->new RecursoNaoEncontradoException("Necessidade nao encontrada."));if(!a.getNecessidades().add(n))throw new RegraNegocioException("Este vinculo ja existe.");return out(repo.save(a),true);}
 @Transactional public AcaoSocialResponse desvincularCampanha(Long id,Long cid){AcaoSocial a=get(id);if(!a.getCampanhas().removeIf(c->c.getId().equals(cid)))throw new RecursoNaoEncontradoException("Vinculo com campanha nao encontrado.");return out(repo.save(a),true);}
 @Transactional public AcaoSocialResponse desvincularNecessidade(Long id,Long nid){AcaoSocial a=get(id);if(!a.getNecessidades().removeIf(n->n.getId().equals(nid)))throw new RecursoNaoEncontradoException("Vinculo com necessidade nao encontrado.");return out(repo.save(a),true);}
 @Transactional(readOnly=true)public List<ParticipacaoResponse> listarParticipacoes(){return participacoes.findAllByOrderByDataRegistroDesc().stream().map(ParticipacaoResponse::de).toList();}
 @Transactional public AcaoSocialResponse vincularParticipacao(Long id,Long pid){AcaoSocial a=get(id);ParticipacaoVoluntario p=participacoes.findById(pid).orElseThrow(()->new RecursoNaoEncontradoException("Participacao nao encontrada."));if(!a.getParticipacoes().add(p))throw new RegraNegocioException("Este vinculo ja existe.");return out(repo.save(a),true);}
 @Transactional public AcaoSocialResponse desvincularParticipacao(Long id,Long pid){AcaoSocial a=get(id);if(!a.getParticipacoes().removeIf(p->p.getId().equals(pid)))throw new RecursoNaoEncontradoException("Vinculo com participacao nao encontrado.");return out(repo.save(a),true);}
 private void validar(AcaoSocialRequest q){if(q.dataFim().isBefore(q.dataInicio()))throw new RegraNegocioException("A data final nao pode ser anterior a inicial.");}private void copiar(AcaoSocial a,AcaoSocialRequest q){a.setTitulo(q.titulo());a.setDescricao(q.descricao());a.setObjetivo(q.objetivo());a.setDataInicio(q.dataInicio());a.setDataFim(q.dataFim());a.setLocal(q.local());a.setPublicoAtendido(q.publicoAtendido());a.setEstimativaBeneficiados(q.estimativaBeneficiados());}private void invalida(){throw new RegraNegocioException("Esta transicao nao e permitida.");}}
