package br.com.bemdoar.service;
import br.com.bemdoar.dto.*;import br.com.bemdoar.entity.*;import br.com.bemdoar.enums.*;import br.com.bemdoar.exception.*;import br.com.bemdoar.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class CandidaturaService{private final CandidaturaRepository repo;private final ParticipacaoVoluntarioRepository participacoes;private final UsuarioRepository usuarios;private final OportunidadeService oportunidades;private final NotificacaoService notificacoes;public CandidaturaService(CandidaturaRepository r,ParticipacaoVoluntarioRepository p,UsuarioRepository u,OportunidadeService o,NotificacaoService n){repo=r;participacoes=p;usuarios=u;oportunidades=o;notificacoes=n;}private Candidatura get(Long id){return repo.findById(id).orElseThrow(()->new RecursoNaoEncontradoException("Candidatura nao encontrada."));}private CandidaturaResponse out(Candidatura c){return CandidaturaResponse.de(c,participacoes.findByCandidaturaId(c.getId()).map(p->p.getResultado().name()).orElse(null));}
 @Transactional public CandidaturaResponse criar(Long uid,Long oportunidadeId){if(repo.existsByUsuarioIdAndOportunidadeIdAndSituacaoIn(uid,oportunidadeId,List.of(SituacaoCandidatura.PENDENTE,SituacaoCandidatura.APROVADA)))throw new RegraNegocioException("Voce ja possui candidatura ativa para esta oportunidade.");Usuario u=usuarios.findById(uid).orElseThrow();OportunidadeVoluntariado o=oportunidades.aberta(oportunidadeId);if(o.getIdadeMinima()!=null&&(u.getDataNascimento()==null||Period.between(u.getDataNascimento(),LocalDate.now()).getYears()<o.getIdadeMinima()))throw new RegraNegocioException("Voce nao possui a idade minima exigida.");Candidatura c=new Candidatura();c.setUsuario(u);c.setOportunidade(o);c.setSituacao(SituacaoCandidatura.PENDENTE);c.setDataCandidatura(LocalDateTime.now());return out(repo.save(c));}
 @Transactional(readOnly=true)public List<CandidaturaResponse> minhas(Long uid){return repo.findByUsuarioIdOrderByDataCandidaturaDesc(uid).stream().map(this::out).toList();}@Transactional(readOnly=true)public List<CandidaturaResponse> porOportunidade(Long id){return repo.findByOportunidadeIdOrderByDataCandidaturaDesc(id).stream().map(this::out).toList();}
 @Transactional public CandidaturaResponse aprovar(Long id){Candidatura c=get(id);if(c.getSituacao()!=SituacaoCandidatura.PENDENTE)invalida();long ocupadas=repo.countByOportunidadeIdAndSituacao(c.getOportunidade().getId(),SituacaoCandidatura.APROVADA);if(ocupadas>=c.getOportunidade().getVagas())throw new RegraNegocioException("Nao ha vagas disponiveis.");c.setSituacao(SituacaoCandidatura.APROVADA);repo.save(c);notificacoes.notificar(c.getUsuario().getId(),"Sua candidatura foi aprovada.");return out(c);}
 @Transactional public CandidaturaResponse recusar(Long id,CancelamentoRequest q){Candidatura c=get(id);if(c.getSituacao()!=SituacaoCandidatura.PENDENTE)invalida();c.setSituacao(SituacaoCandidatura.RECUSADA);c.setMotivoRecusa(q==null?null:q.motivo());repo.save(c);notificacoes.notificar(c.getUsuario().getId(),"Sua candidatura foi recusada.");return out(c);}
 @Transactional public CandidaturaResponse cancelar(Long id,Long uid,boolean admin){Candidatura c=get(id);if(!admin&&!c.getUsuario().getId().equals(uid))throw new org.springframework.security.access.AccessDeniedException("Sem permissao");if(c.getSituacao()!=SituacaoCandidatura.PENDENTE&&c.getSituacao()!=SituacaoCandidatura.APROVADA)invalida();c.setSituacao(SituacaoCandidatura.CANCELADA);return out(repo.save(c));}
 @Transactional public CandidaturaResponse participacao(Long id,ParticipacaoRequest q){Candidatura c=get(id);if(c.getSituacao()!=SituacaoCandidatura.APROVADA)throw new RegraNegocioException("Somente voluntarios aprovados podem receber registro de participacao.");if(participacoes.existsByCandidaturaId(id))throw new RegraNegocioException("A participacao desta candidatura ja foi registrada.");ParticipacaoVoluntario p=new ParticipacaoVoluntario();p.setCandidatura(c);p.setResultado(q.resultado());p.setObservacao(q.observacao());p.setDataRegistro(LocalDateTime.now());participacoes.save(p);return out(c);}private void invalida(){throw new RegraNegocioException("Esta transicao nao e permitida.");}}
