package br.com.bemdoar.service;
import br.com.bemdoar.dto.*; import br.com.bemdoar.entity.*; import br.com.bemdoar.enums.*; import br.com.bemdoar.exception.*; import br.com.bemdoar.repository.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service public class DoacaoService {
 private final DoacaoRepository repo; private final NecessidadeService necessidades; private final CampanhaService campanhas; private final UsuarioRepository usuarios; private final NotificacaoService notificacoes;
 public DoacaoService(DoacaoRepository r,NecessidadeService n,CampanhaService c,UsuarioRepository u,NotificacaoService no){repo=r;necessidades=n;campanhas=c;usuarios=u;notificacoes=no;}
 private Doacao get(Long id){return repo.findById(id).orElseThrow(()->new RecursoNaoEncontradoException("Doacao nao encontrada."));}
 @Transactional public DoacaoResponse criar(Long usuarioId,DoacaoRequest q){if(q.necessidadeId()==null&&q.campanhaId()==null) throw new RegraNegocioException("Informe uma necessidade ou campanha."); Doacao d=new Doacao(); d.setUsuario(usuarios.findById(usuarioId).orElseThrow());
  if(q.necessidadeId()!=null)d.setNecessidade(necessidades.buscarDisponivelOuFalhar(q.necessidadeId())); if(q.campanhaId()!=null){Campanha c=campanhas.buscarDisponivelOuFalhar(q.campanhaId()); if(q.necessidadeId()!=null&&!c.getNecessidades().contains(d.getNecessidade())) throw new RegraNegocioException("A necessidade nao pertence a esta campanha."); d.setCampanha(c);}
  d.setItem(q.item());d.setQuantidade(q.quantidade());d.setObservacao(q.observacao());d.setFormaEntrega(q.formaEntrega());d.setSituacao(SituacaoDoacao.PENDENTE);d.setDataRegistro(LocalDateTime.now());return DoacaoResponse.de(repo.save(d));}
 @Transactional(readOnly=true) public List<DoacaoResponse> minhas(Long uid){return repo.findByUsuarioIdOrderByDataRegistroDesc(uid).stream().map(DoacaoResponse::de).toList();}
 @Transactional(readOnly=true) public List<DoacaoResponse> listar(SituacaoDoacao s){return (s==null?repo.findAll():repo.findBySituacaoOrderByDataRegistroDesc(s)).stream().map(DoacaoResponse::de).toList();}
 @Transactional(readOnly=true) public DoacaoResponse buscar(Long id,Long uid,boolean admin){Doacao d=get(id); if(!admin&&!d.getUsuario().getId().equals(uid)) throw new org.springframework.security.access.AccessDeniedException("Sem permissao"); return DoacaoResponse.de(d);}
 @Transactional public DoacaoResponse confirmar(Long id){Doacao d=get(id); exigir(d,SituacaoDoacao.PENDENTE);d.setSituacao(SituacaoDoacao.CONFIRMADA);d.setDataConfirmacao(LocalDateTime.now());repo.save(d);notificacoes.notificar(d.getUsuario().getId(),"Sua doacao foi confirmada.");return DoacaoResponse.de(d);}
 @Transactional public DoacaoResponse receber(Long id){Doacao d=get(id);exigir(d,SituacaoDoacao.CONFIRMADA);d.setSituacao(SituacaoDoacao.RECEBIDA);d.setDataRecebimento(LocalDateTime.now());repo.save(d);if(d.getNecessidade()!=null)necessidades.recalcularProgresso(d.getNecessidade().getId());notificacoes.notificar(d.getUsuario().getId(),"Sua doacao foi recebida.");return DoacaoResponse.de(d);}
 @Transactional public DoacaoResponse cancelar(Long id,Long uid,boolean admin,CancelamentoRequest q){Doacao d=get(id);if(!admin&&!d.getUsuario().getId().equals(uid))throw new org.springframework.security.access.AccessDeniedException("Sem permissao");if(d.getSituacao()!=SituacaoDoacao.PENDENTE&&d.getSituacao()!=SituacaoDoacao.CONFIRMADA)invalida();if(admin&&(q==null||q.motivo()==null||q.motivo().isBlank()))throw new RegraNegocioException("Informe o motivo do cancelamento.");d.setMotivoCancelamento(q==null?null:q.motivo());d.setSituacao(SituacaoDoacao.CANCELADA);return DoacaoResponse.de(repo.save(d));}
 private void exigir(Doacao d,SituacaoDoacao s){if(d.getSituacao()!=s)invalida();} private void invalida(){throw new RegraNegocioException("Esta transicao nao e permitida.");}
}
