package br.com.bemdoar.service;
import br.com.bemdoar.dto.*;import br.com.bemdoar.entity.*;import br.com.bemdoar.enums.*;import br.com.bemdoar.exception.*;import br.com.bemdoar.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class OportunidadeService{private final OportunidadeVoluntariadoRepository repo;private final CandidaturaRepository candidaturas;public OportunidadeService(OportunidadeVoluntariadoRepository r,CandidaturaRepository c){repo=r;candidaturas=c;}private OportunidadeVoluntariado get(Long id){return repo.findById(id).orElseThrow(()->new RecursoNaoEncontradoException("Oportunidade nao encontrada."));}private OportunidadeResponse out(OportunidadeVoluntariado o){return OportunidadeResponse.de(o,candidaturas.countByOportunidadeIdAndSituacao(o.getId(),SituacaoCandidatura.APROVADA));}
 @Transactional(readOnly=true)public List<OportunidadeResponse> listar(){return repo.findAllByOrderByDataAtividadeDesc().stream().map(this::out).toList();}@Transactional(readOnly=true)public OportunidadeResponse buscar(Long id){return out(get(id));}
 @Transactional public OportunidadeResponse criar(OportunidadeRequest q){OportunidadeVoluntariado o=new OportunidadeVoluntariado();copiar(o,q);o.setSituacao(SituacaoOportunidade.PLANEJADA);return out(repo.save(o));}
 @Transactional public OportunidadeResponse editar(Long id,OportunidadeRequest q){OportunidadeVoluntariado o=get(id);long ocupadas=candidaturas.countByOportunidadeIdAndSituacao(id,SituacaoCandidatura.APROVADA);if(q.vagas()<ocupadas)throw new RegraNegocioException("Nao e possivel reduzir as vagas abaixo do numero de aprovados.");copiar(o,q);return out(repo.save(o));}
 @Transactional public OportunidadeResponse abrir(Long id){OportunidadeVoluntariado o=get(id);if(o.getSituacao()!=SituacaoOportunidade.PLANEJADA)invalida();o.setSituacao(SituacaoOportunidade.ABERTA);return out(repo.save(o));}
 @Transactional public OportunidadeResponse encerrar(Long id){OportunidadeVoluntariado o=get(id);if(o.getSituacao()!=SituacaoOportunidade.PLANEJADA&&o.getSituacao()!=SituacaoOportunidade.ABERTA)invalida();o.setSituacao(SituacaoOportunidade.ENCERRADA);return out(repo.save(o));}
 @Transactional(readOnly=true)public OportunidadeVoluntariado aberta(Long id){OportunidadeVoluntariado o=get(id);if(o.getSituacao()!=SituacaoOportunidade.ABERTA)throw new RegraNegocioException("Esta oportunidade nao esta aberta.");return o;}private void copiar(OportunidadeVoluntariado o,OportunidadeRequest q){o.setTitulo(q.titulo());o.setDescricao(q.descricao());o.setAtividade(q.atividade());o.setVagas(q.vagas());o.setDataAtividade(q.dataAtividade());o.setHorario(q.horario());o.setLocal(q.local());o.setIdadeMinima(q.idadeMinima());o.setRequisitos(q.requisitos());}private void invalida(){throw new RegraNegocioException("Esta transicao nao e permitida.");}}
